101 = net.solarnetwork.sunspec.core.inverter.IntegerInverterModelAccessor
102 = net.solarnetwork.sunspec.core.inverter.IntegerInverterModelAccessor
103 = net.solarnetwork.sunspec.core.inverter.IntegerInverterModelAccessor

111 = net.solarnetwork.sunspec.core.inverter.FloatingPointInverterModelAccessor
112 = net.solarnetwork.sunspec.core.inverter.FloatingPointInverterModelAccessor
113 = net.solarnetwork.sunspec.core.inverter.FloatingPointInverterModelAccessor

120 = net.solarnetwork.sunspec.core.inverter.InverterNameplateRatingsModelAccessorImpl
121 = net.solarnetwork.sunspec.core.inverter.InverterBasicSettingsModelAccessorImpl
122 = net.solarnetwork.sunspec.core.inverter.InverterExtendedMeasurementsModelAccessorImpl
123 = net.solarnetwork.sunspec.core.inverter.InverterImmediateControlsModelAccessorImpl
124 = net.solarnetwork.sunspec.core.inverter.InverterBasicStorageControlsModelAccessorImpl
125 = net.solarnetwork.sunspec.core.inverter.InverterPricingSignalModelAccessorImpl

160 = net.solarnetwork.sunspec.core.inverter.InverterMpptExtensionModelAccessorImpl

201 = net.solarnetwork.sunspec.core.meter.IntegerMeterModelAccessor
202 = net.solarnetwork.sunspec.core.meter.IntegerMeterModelAccessor
203 = net.solarnetwork.sunspec.core.meter.IntegerMeterModelAccessor
204 = net.solarnetwork.sunspec.core.meter.IntegerMeterModelAccessor

211 = net.solarnetwork.sunspec.core.meter.FloatingPointMeterModelAccessor
212 = net.solarnetwork.sunspec.core.meter.FloatingPointMeterModelAccessor
213 = net.solarnetwork.sunspec.core.meter.FloatingPointMeterModelAccessor
214 = net.solarnetwork.sunspec.core.meter.FloatingPointMeterModelAccessor

302 = net.solarnetwork.sunspec.core.environmental.IrradianceModelAccessorImpl
303 = net.solarnetwork.sunspec.core.environmental.BomTemperatureModelAccessorImpl
304 = net.solarnetwork.sunspec.core.environmental.InclinometerModelAccessorImpl
305 = net.solarnetwork.sunspec.core.environmental.GpsModelAccessorImpl
306 = net.solarnetwork.sunspec.core.environmental.ReferencePointModelAccessorImpl
307 = net.solarnetwork.sunspec.core.environmental.MeteorologicalModelAccessorImpl
308 = net.solarnetwork.sunspec.core.environmental.MiniMeteorologicalModelAccessorImpl

401 = net.solarnetwork.sunspec.core.combiner.StringCombinerModelAccessorImpl
402 = net.solarnetwork.sunspec.core.combiner.StringCombinerAdvancedModelAccessorImpl
403 = net.solarnetwork.sunspec.core.combiner.StringCombinerModelAccessorImpl
404 = net.solarnetwork.sunspec.core.combiner.StringCombinerAdvancedModelAccessorImpl

701 = net.solarnetwork.sunspec.core.der.DerAcMeasurementModelAccessorImpl
702 = net.solarnetwork.sunspec.core.der.DerCapacityModelAccessorImpl
703 = net.solarnetwork.sunspec.core.der.DerEnterServiceModelAccessorImpl
704 = net.solarnetwork.sunspec.core.der.DerAcControlsModelAccessorImpl
705 = net.solarnetwork.sunspec.core.der.DerVoltVarModelAccessorImpl
706 = net.solarnetwork.sunspec.core.der.DerVoltWattModelAccessorImpl
707 = net.solarnetwork.sunspec.core.der.DerTripLowVoltageModelAccessorImpl
708 = net.solarnetwork.sunspec.core.der.DerTripHighVoltageModelAccessorImpl
709 = net.solarnetwork.sunspec.core.der.DerTripLowFrequencyModelAccessorImpl
710 = net.solarnetwork.sunspec.core.der.DerTripHighFrequencyModelAccessorImpl
711 = net.solarnetwork.sunspec.core.der.DerFrequencyDroopModelAccessorImpl
712 = net.solarnetwork.sunspec.core.der.DerWattVarModelAccessorImpl
713 = net.solarnetwork.sunspec.core.der.DerStorageCapacityModelAccessorImpl
714 = net.solarnetwork.sunspec.core.der.DerDcMeasurementModelAccessorImpl
715 = net.solarnetwork.sunspec.core.der.DerControlModelAccessorImpl

802 = net.solarnetwork.sunspec.core.storage.BatteryBaseModelAccessorImpl
803 = net.solarnetwork.sunspec.core.storage.LithiumIonBankModelAccessorImpl
804 = net.solarnetwork.sunspec.core.storage.LithiumIonStringModelAccessorImpl
805 = net.solarnetwork.sunspec.core.storage.LithiumIonModuleModelAccessorImpl
