plugins {
    id 'java-library'
    id 'biz.aQute.bnd.builder'
}

apply plugin: 'java-library'

description = 'Nifty SunSpec: API'

dependencies {
	implementation "org.jspecify:jspecify:${rootProject.ext.jSpecifyVersion}"
	
	implementation("net.solarnetwork.common:net.solarnetwork.common:${rootProject.ext.snCommonVersion}") {
		transitive = false
	}

	// Testing
	testImplementation project(':nifty-sunspec-test')
}

jar.manifest {
    attributes('Implementation-Version': version)
}

tasks.withType(Jar).matching { it.name.contains('sources') }.configureEach {
	manifest {
		attributes(
			'Bundle-SymbolicName': 'net.solarnetwork.sunspec.api.sources',
			'Bundle-Name': 'SolarNetwork SunSpec API Sources',
			'Bundle-Version': version,
			'Bundle-ManifestVersion': '2',
			'Eclipse-SourceBundle': 'net.solarnetwork.sunspec.api;version="'
				+ version + '";roots:="."'
		)
	}
}
